version: 0.2

env:
  shell: powershell.exe

phases:
  build:
    commands:
      - Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - choco install python --confirm --no-progress
      - choco install curl --confirm --no-progress
      - python -m venv .venv
      - .venv\Scripts\activate
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - python get-pip.py
      - pip install --upgrade pyinstaller
      - pip install -r requirements.txt
      - pyinstaller --name aws-auto-inventory-windows-amd64 --clean --onefile --hidden-import cmath --log-level=DEBUG cli.py
artifacts:
  files:
    - dist\*