version: 0.2

phases:
  pre_build:
    commands:
      - echo 'Install Make'
      - apt-get install -y build-essential
  build:
    commands:
      - make docker/build/ubuntu
  post_build:
    commands:
      - make docker/push/ubuntu
artifacts:
  files:
    - 'dist/*'