# AWS Auto Inventory looks for the following locations, copy and paste this sample config, (without -sample in its file name )at:

# Here are the default search paths for each platform:
# OS X: ~/.config/aws-auto-inventory and ~/Library/Application Support/aws-auto-inventory
# Other Unix: $XDG_CONFIG_HOME/aws-auto-inventory and ~/.config/aws-auto-inventory
# Windows: %APPDATA%\aws-auto-inventory where the APPDATA environment variable falls back to %HOME%\AppData\Roaming if undefined

aws:
  profile: my-aws-profile
  region: 
    - us-east-1

excel:
  transpose: True

inventory:
  - sheet1:
      name: EC2 # sheet name on Excel
      service: ec2 # the boto3 client of an AWS service
      function: describe_instances # the client method of the service defined above
      result_key: Reservations # [optional]: The first key of the response dict
  - sheet2:
      name: EC2 # sheet name on Excel
      service: ec2 # the boto3 client of an AWS service
      function: describe_instances # the client method of the service defined above
      result_key: Reservations # [optional]: The first key of the response dict
  - sheet2:
      name: EBS
      service: ec2
      function: describe_volumes
      result_key: Volumes