name: Build
on: [push]
jobs:
  linux-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, pypy3]
        architecture: 'x64' 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: python3 --version
    - run: pip install --upgrade pip
    - run: pip install --upgrade pyinstaller
    - run: pip install -r requirements.txt
    - run: pyinstaller --name aws-auto-inventory --clean --onefile --hidden-import cmath --log-level=DEBUG cli.py
