name: Build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - run: python --version
    - run: pip install --upgrade pip
    - run: pip install --upgrade pyinstaller
    - run: pip install -r requirements.txt
    - run: pyinstaller --name aws-auto-inventory --clean --onefile --hidden-import cmath --log-level=DEBUG app/cli.py
