name: Hygiene

on:
  push:

permissions:
  contents: read

jobs:
  code-hygiene:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Install pre-commit hooks and execute rules
        run: pre-commit run --all-files

  doc-hygiene:
    needs: code-hygiene
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Create virtualenv
        run: python -m venv .venv

      - name: Build documentation
        run: make doc/build

      - name: Check documentation status
        run: git diff --exit-code # exit 1 if there's a difference between what was pushed with what was produced by doc/build.
