name: Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python3 --version
      - run: pip install --upgrade pip
      - run: pip install --upgrade pyinstaller
      - run: pip install -r requirements.txt
      - run: pyinstaller --name aws-auto-inventory-${{ matrix.os }} --clean --onefile --hidden-import cmath --log-level=DEBUG cli.py
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-latest'
        with:
          name: aws-auto-inventory-${{ matrix.os }}
          path: dist\aws-auto-inventory-windows-latest.exe
      - uses: actions/upload-artifact@v2
        if: matrix.os != 'windows-latest'
        with:
          name: aws-auto-inventory-${{ matrix.os }}
          path: ./dist/aws-auto-inventory-${{ matrix.os }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: aws-auto-inventory-ubuntu-latest
      - uses: actions/download-artifact@v2
        with:
          name: aws-auto-inventory-macos-latest
      - uses: actions/download-artifact@v2
        with:
          name: aws-auto-inventory-windows-latest
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            aws-auto-inventory-ubuntu-latest
            aws-auto-inventory-macos-latest
            aws-auto-inventory-windows-latest.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}